spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: STUDENT-SERVICE

server:
  port: 8081
